In [2]:
import numpy as np

In [3]:
gene1 = [100,200,50,400]
gene2 = [50,0,0,100]
gene3 = [350,100,50,200]
expression_data = [gene1,gene2,gene3]

In [4]:
expression_data

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [8]:
a = np.array(expression_data)
a   
    
    
      

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [ ]:
#SLICING
#linspace(100,50,5)

In [10]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [11]:
np.random.randint(10,100,4)

array([93, 71, 35, 49])

In [12]:
np.ones(10,int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
 A = np.array([6,10,12,11,7])
H = A + 4
H



array([10, 14, 16, 15, 11])

In [ ]:
#DIFFERENT TYPES OF ARRAYS



In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
 np.random.randint(3,size=(3,3))

array([[1, 0, 2],
       [1, 1, 2],
       [2, 0, 0]])

In [16]:
np.identity(2,dtype='int32')

array([[1, 0],
       [0, 1]])

In [ ]:
#MATHMATICS,sin,cos,tan,

In [19]:
np.tan(90)

-1.995200412208242

In [4]:
np.cos(90)

-0.4480736161291701

In [5]:
np.sin(90)

0.8939966636005579